[package]
name = "rust_embedder_app"
version = "0.1.0"
authors = ["Brandon Fish <brandon.j.fish@gmail.com>"]
edition = "2018"

[dependencies]
wasmer-runtime = {git = "https://github.com/wasmerio/wasmer.git", rev="4e1bc483a885e3af0a4f981a8aa7d28b6045c199"}
