[package]
name = "rust_embedder_app"
version = "0.1.0"
authors = ["Brandon Fish <brandon.j.fish@gmail.com>"]
edition = "2018"

[dependencies]
wasmer-runtime = {git = "https://github.com/wasmerio/wasmer.git", rev="1886b3d3c1c78a47ffd6a83bc5b639c637e862bc"}
